spring:
  datasource:
    username: root
    password: hpoj1536..++
    url: jdbc:mysql://47.103.3.1:3306/mahjong_account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 47.103.3.1
    port: 6370
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml